services:
  backend:
    build:
      context: ./backend
    ports:
      - "3200:3200"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "npm install && npm run build && node dist/main.js"
    restart: always
    
  frontend:
    build:
      context: ./frontend
    ports:
      - "3201:3201"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "npm install && npm run build"
